@echo off
echo Configurando Node.js...
nvs use node/22.19.0/x64
echo Cambiando al directorio frontend...
cd /d "c:\Users\Ivancho\Desktop\Hotel\frontend"
echo Ejecutando Angular...
npm start
pause